# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
jobs:
  page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          cache: npm
      - run: npm i
      - run: npm run format:check
name: Format
on: pull_request
permissions:
  contents: read
