# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
jobs:
  page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
      - run: bun i
      - run: bun format:check
name: Format
on: pull_request
permissions:
  contents: read
