# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
jobs:
  page:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          filter: blob:none
          submodules: recursive
      - uses: actions/setup-node@main
        with:
          cache: npm
      - run: npm i
      - run: npm run format:check
      - uses: awalsh128/cache-apt-pkgs-action@5513791f75b039e2a79653b1a92238d3fb8d99b4
        with:
          packages: pandoc
      - uses: chetan/git-restore-mtime-action@d186aca54f8760da4dec55313195e51ed3ebb0b3
      - run: npm run generate
      - uses: actions/upload-pages-artifact@main
        with:
          path: public
      - uses: actions/deploy-pages@main
name: Page
on:
  push:
    branches: [master]
permissions:
  contents: read
  id-token: write
  pages: write
